### PR TITLE
quick gitignore stuff

### PR DESCRIPTION
**Pull request by Chovin**
feel free to add your own

### CODE REVIEW

**Comment by Chovin** [comment]
yo dude, every PR doesn't need to match. I'm reverting your changes and merging this PR so that you understand.
These are **feature branches**, not the new master. Every PR doesn't need to have every change

**Comment by Chovin** [comment]
Because the change is tiny and has no effect on the project, taking the liberty to merge in a few hours... Once i revert

**Comment by ghost** [comment]
I don't remember ever pushing to this branch. I don't know why it says I have...

**Comment by gabrielcerteza** [comment]
It says I've committed 2 days ago, which was before the creation of this PR. How is that even possible?

**Comment by Chovin** [comment]
Oh shoot, that's super weird. Sorry, looking at this on mobile is disorientating. 
I'll work this out locally, see what happened.
Looks like `git stash branch` doesn't move only the stashed commits
The blame is all on me

**Comment by Chovin** [comment]
closed because lack of activity. also not relevant anymore

**Pull request closed without merging**
