### PR TITLE
Initial commit for 2nd version of website

### PR DESCRIPTION
**Pull request by rcmanglona**

### CODE REVIEW

**Comment by Chovin** [comment]
having the same issue with github trying to build bootstrap's jekyll junk.
I think this was fixed the 1st time here 0990e006c338c84ae5e1d67fcb1a371610a2e63f

I'll fix it again as soon as I can so that we can move forward.
There's gotta be a simpler way to use bootstrap on github.

**Comment by gabrielcerteza** [comment]
@rmanglona where are you getting Bootstrap from? It might be better to grab the Bootstrap library off of their website instead of cloning the entire repo for Bootstrap's website. 

Here's a link to Bootstrap's website: [https://getbootstrap.com/getting-started/](url)

Lastly, why don't you want to use a CDN that is hosting Bootstrap? What is the main concern?

**Comment by Chovin** [comment]
we've decided to go with this layout, so we can merge now and pull in past changes if we need to.
@gabrielcerteza @jasperdanan please give 👍  for this if you agree.
either way, work can be continued on my end.

**Comment by Chovin** [comment]
so I think we have 2 choices on the jekyll bug though.
1. push the previous patch to fix the bootstrap-jekyll issue by just removing random files
2. remove bootstrap source and link anything and everything we can. keeping only the minified file(s) we need and fonts and such that we can't find hosted

please vote in reactions:
❤️  for 1.
🎉  for 2.

**Comment by Chovin** [comment]
this seems to be broken. I will look into it soon.
image

**Comment by Chovin** [comment]
we got 2 votes for 2. :tada:..
but I already had Jake PR 1. :heart: to this PR :P
1. :heart: will get it building on github so we can actually view it.
I'm gonna keep pushing for that fix since it's done already and then we'll work on 2. :tada: as we go. 
They aren't mutually exclusive.
sound good?

**Comment by Chovin** [comment]
no movement, so I will merge and continue with the proposed plan. :+1:

**Pull request merged**
