### PR TITLE
Multiple pages

### PR DESCRIPTION
**Pull request by ghost**
I've created js, css, and html folders that will store respective file extensions in each folder, and I've linked external js, css, and html files. 

I've created a header.html file which is our navbar, and it'll be loaded onto page with jQuery.

For now, we'll be using the front-end to create multiple pages. Eventually, we'll be able to take care of routing once we pick a server-side language.

Comment below if you have any questions.

### CODE REVIEW

**Comment by ghost** [comment]
This will be merged tonight unless someone rebukes.

**Comment by Chovin** [comment]
Technically unfinished since we can't see if the header can be added in through the addition of jQuery.
It is an improvement though.
once our page is deployed to the public, let's not let PRs like this merge.

**Comment by ghost** [comment]
What do you mean we can't see if the header can be added in through the addition of jQuery?

**Comment by Chovin** [comment]
this PR makes a promise that something it removed from the user's vision will be able to be put back in later.
it's an unfinished improvement. ie. it's in development. it should be in a development branch.
technically it's "breaking" something.

It's an improvement to the current structure though and our site isn't deployed yet so it's fine for now but, imo, PRs like this shouldn't be accepted in the future if we're following Github Flow

**Comment by ghost** [comment]
The PR doesn't remove anything from the user's vision. I just moved the header into a separate file that'll be loaded onto all pages via jQuery. I don't really understand what you mean, sorry.

**Comment by ghost** [comment]
Closing PR to edit features before making another PR.

**Comment by Chovin** [comment]
my mistake, just didn't have webserver up when testing and didn't see the js you added :3

**Comment by jasperdanan** [comment]
d2b675c Added in this branch: custom.css for any bootstrap override

**Comment by Chovin** [comment]
@gabrielcerteza we can't check the PR if you keep committing to it.
please comment on this -> #27

**Comment by ghost** [comment]
I only moved Jasper's changes into a consolidated css file.

**Comment by Chovin** [comment]
you said to keep the branch until the feature is complete in #27. Please request a code review once it is complete so we know when to review and give our 👍

**Comment by gabrielcerteza** [comment]
Please review code.

**Comment by ghost** [comment]
If two people pushed two different features to the branch, then shouldn't
we just merge it already? We're only missing the projects page because we
don't have a design for it yet. I'll just link it to some random page and
prompt for a code review.

**Comment by Chovin** [comment]
No. PRs should only be merged if 2 or more people have reviewed all the changes made. As soon as one person pushes to this branch the reviewing process has to start over. Keep doing that over and over and you're just wasting people's time.

Making a PR for review and convo is fine but you should call off the time limit if you're going to continue working on the PR

**Comment by jasperdanan** [comment]
Any update on the pull request?

**Comment by Chovin** [comment]
I thought this was a WIP pr? @gabe, what are your intentions with this PR?

**Comment by jasperdanan** [comment]
Confirming PR
- No Issues
- Not updated for a month

**Pull request merged**
